export const equipmentCategories = [
  "safety",
  "comfort",
  "interior",
  "infotainment",
  "exterior",
  "parking",
  "electric",
] as const;
export type EquipmentCategory = (typeof equipmentCategories)[number];

export const equipmentCatalog = [
  ["ADAPTIVE_CRUISE_CONTROL", "safety", true],
  ["CRUISE_CONTROL", "safety", false],
  ["LANE_KEEP_ASSIST", "safety", true],
  ["LANE_CHANGE_WARNING", "safety", false],
  ["BLIND_SPOT_MONITOR", "safety", true],
  ["AUTONOMOUS_EMERGENCY_BRAKING", "safety", false],
  ["COLLISION_WARNING", "safety", false],
  ["FRONT_PARKING_SENSORS", "safety", true],
  ["REAR_PARKING_SENSORS", "safety", true],
  ["SURROUND_VIEW_CAMERA", "safety", true],
  ["REAR_VIEW_CAMERA", "safety", true],
  ["NIGHT_VISION", "safety", false],
  ["TRAFFIC_SIGN_RECOGNITION", "safety", false],
  ["DRIVER_FATIGUE_WARNING", "safety", false],
  ["ADAPTIVE_HEADLIGHTS", "safety", false],
  ["AUTOMATIC_HIGH_BEAM", "safety", false],
  ["LED_HEADLIGHTS", "safety", false],
  ["MATRIX_LED", "safety", true],
  ["LASER_LIGHTS", "safety", false],
  ["CORNERING_LIGHTS", "safety", false],
  ["COMFORT_SEATS", "comfort", false],
  ["POWER_SEATS", "comfort", true],
  ["MEMORY_POWER_SEATS", "comfort", true],
  ["VENTILATED_SEATS", "comfort", false],
  ["MASSAGE_SEATS", "comfort", false],
  ["HEATED_FRONT_SEATS", "comfort", true],
  ["HEATED_REAR_SEATS", "comfort", false],
  ["HEATED_STEERING_WHEEL", "comfort", true],
  ["CLIMATE_CONTROL", "comfort", false],
  ["TWO_ZONE_CLIMATE", "comfort", false],
  ["THREE_ZONE_CLIMATE", "comfort", false],
  ["FOUR_ZONE_CLIMATE", "comfort", false],
  ["AIR_SUSPENSION", "comfort", true],
  ["ADAPTIVE_CHASSIS", "comfort", true],
  ["SOFT_CLOSE", "comfort", false],
  ["COMFORT_ACCESS", "comfort", true],
  ["KEYLESS_ENTRY", "comfort", true],
  ["KEYLESS_START", "comfort", true],
  ["POWER_TAILGATE", "comfort", true],
  ["REMOTE_TAILGATE", "comfort", false],
  ["PARKING_HEATER", "comfort", true],
  ["FUEL_HEATER", "comfort", false],
  ["REMOTE_HEATER", "comfort", false],
  ["CABIN_HEATER", "comfort", false],
  ["LEATHER", "interior", true],
  ["FULL_LEATHER", "interior", false],
  ["HALF_LEATHER", "interior", false],
  ["ALCANTARA", "interior", false],
  ["SPORT_SEATS", "interior", false],
  ["SPORT_PACKAGE_SEATS", "interior", false],
  ["POWER_ADJUSTABLE_STEERING_WHEEL", "interior", false],
  ["MULTIFUNCTION_STEERING_WHEEL", "interior", false],
  ["AMBIENT_LIGHTING", "interior", true],
  ["DIGITAL_INSTRUMENT_CLUSTER", "interior", true],
  ["HEAD_UP_DISPLAY", "interior", true],
  ["SUN_BLINDS", "interior", false],
  ["ISOFIX", "interior", false],
  ["SEVEN_SEATS", "interior", false],
  ["THIRD_ROW_SEATS", "interior", false],
  ["APPLE_CARPLAY", "infotainment", true],
  ["ANDROID_AUTO", "infotainment", true],
  ["NAVIGATION", "infotainment", true],
  ["BLUETOOTH", "infotainment", false],
  ["WIRELESS_PHONE_CHARGING", "infotainment", false],
  ["USB_C", "infotainment", false],
  ["HARMAN_KARDON", "infotainment", true],
  ["BOSE", "infotainment", true],
  ["BOWERS_WILKINS", "infotainment", true],
  ["BANG_OLUFSEN", "infotainment", true],
  ["DYNAUDIO", "infotainment", true],
  ["BURMESTER", "infotainment", true],
  ["MERIDIAN", "infotainment", false],
  ["JBL", "infotainment", false],
  ["MARK_LEVINSON", "infotainment", false],
  ["PREMIUM_SOUND_SYSTEM", "infotainment", false],
  ["DAB_RADIO", "infotainment", false],
  ["M_SPORT_PACKAGE", "exterior", false],
  ["AMG_PACKAGE", "exterior", false],
  ["S_LINE", "exterior", false],
  ["R_LINE", "exterior", false],
  ["BLACK_PACKAGE", "exterior", false],
  ["PANORAMIC_ROOF", "exterior", true],
  ["SUNROOF", "exterior", true],
  ["TINTED_WINDOWS", "exterior", true],
  ["INTEGRATED_SUN_BLINDS", "exterior", false],
  ["POWER_FOLDING_MIRRORS", "exterior", false],
  ["AUTO_DIMMING_MIRRORS", "exterior", false],
  ["TOW_HITCH", "exterior", true],
  ["ELECTRIC_TOW_HITCH", "exterior", false],
  ["DETACHABLE_TOW_HITCH", "exterior", false],
  ["ROOF_RAILS", "exterior", false],
  ["EXTERIOR_STYLING_PACKAGE", "exterior", false],
  ["AUTOMATIC_PARKING", "parking", true],
  ["PARKING_ASSISTANT", "parking", false],
  ["REMOTE_PARKING", "parking", false],
  ["HEAT_PUMP", "electric", false],
  ["BATTERY_PRECONDITIONING", "electric", false],
  ["FAST_CHARGING", "electric", false],
  ["THREE_PHASE_CHARGING", "electric", false],
  ["CHARGING_CABLE", "electric", false],
  ["VEHICLE_TO_LOAD", "electric", false],
  ["ELECTRIC_CABIN_PREHEATING", "electric", false],
] as const;

export type EquipmentKey = (typeof equipmentCatalog)[number][0];
export const equipmentKeys = equipmentCatalog.map(([key]) => key) as [
  EquipmentKey,
  ...EquipmentKey[],
];
export const commonEquipment = equipmentCatalog
  .filter(([, , common]) => common)
  .map(([key]) => key);
export const isEquipmentKey = (value: string): value is EquipmentKey =>
  (equipmentKeys as readonly string[]).includes(value);

export function normalizeEquipment(values: readonly string[]): EquipmentKey[] {
  if (values.some((value) => !isEquipmentKey(value)))
    throw new Error("INVALID_EQUIPMENT");
  return [...new Set(values)] as EquipmentKey[];
}
